#!/usr/bin/env bash
cmake -G"Xcode" -Tbuildsystem=1 -B./build \
  -DMACOSX=TRUE \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10 \
  -DCMAKE_OSX_SYSROOT=macosx \
  -DCMAKE_OSX_ARCHITECTURES=x86_64 \
  -DENGINE_UNITY_BUILD=ON \
  -DMAKER_OPTION_XCODE_ARCHIVE_SUPPORT=OFF

